---
- hosts: localhost
  vars:
    - docker_compose_version: 1.18.0
    - cert_path: "/home/coyo/certificate"
    - pempath: "{{ cert_path }}/{{ coyo_url }}.pem"
    - csrpath: "{{ cert_path }}/{{ coyo_url }}.csr"
    - cert: "{{ cert_path }}/{{ coyo_url }}.crt"
    - cert_combined: "{{ cert_path }}/{{ coyo_url }}-combined.crt"
  become: yes
  tasks:
  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: enable and start docker
    systemd:
      name: docker.service
      state: started
      enabled: yes

  - name: Install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755

  - name: Create the user 'coyo'
    user:
      name: coyo
      groups:
        - sudo
        - docker
      append: yes

  - name: Create COYO data folder
    file:
      path: /home/coyo/coyo-data
      state: directory
      owner: coyo
      group: coyo
      mode: 0755

  - name: Download and extract COYO
    unarchive:
      src: "https://download.coyoapp.com/release/enterprise/coyo4_{{ coyo_version }}-RELEASE.zip"
      dest: /home/coyo/
      owner: coyo
      group: coyo
      remote_src: yes
      creates: /home/coyo/docker-compose.yml
  - name: Read scripts from extracted file
    find:
      paths: /home/coyo
      patterns: '*.sh'
    register: scripts
  - name: Make extracted scripts executable
    file:
      path: "{{ item.path }}"
      mode: '0755'
    with_items: "{{ scripts.files }}"

  - name: Substitute COYO backend URL
    lineinfile:
      path: /home/coyo/.env
      regexp: '^COYO_BACKEND_URL='
      line: 'COYO_BACKEND_URL={{ coyo_url }}'
  - name: Substitute COYO frontend URL
    lineinfile:
      path: /home/coyo/.env
      regexp: '^COYO_FRONTEND_URL='
      line: 'COYO_FRONTEND_URL={{ coyo_url }}'
  - name: Substitute COYO profile mode
    lineinfile:
      path: /home/coyo/.env
      regexp: '^COYO_PROFILE='
      line: 'COYO_PROFILE={{ coyo_profile }}'
  - name: Substitute COYO management user
    lineinfile:
      path: /home/coyo/.env
      regexp: '^COYO_MANAGEMENT_USER='
      line: 'COYO_MANAGEMENT_USER={{ coyo_management_user }}'
  - name: Substitute COYO management password
    lineinfile:
      path: /home/coyo/.env
      regexp: '^COYO_MANAGEMENT_PASSWORD='
      line: 'COYO_MANAGEMENT_PASSWORD={{ coyo_management_user }}'
  - name: Substitute COYO database name
    lineinfile:
      path: /home/coyo/.env
      regexp: '^COYO_DB_NAME='
      line: 'COYO_DB_NAME={{ coyo_db_name }}'
  - name: Substitute COYO database user
    lineinfile:
      path: /home/coyo/.env
      regexp: '^COYO_DB_USER='
      line: 'COYO_DB_USER={{ coyo_db_user }}'
  - name: Substitute COYO database password
    lineinfile:
      path: /home/coyo/.env
      regexp: '^COYO_DB_PASSWORD='
      line: 'COYO_DB_PASSWORD={{ coyo_db_password }}'

  - name: Create directory for SSL certificates
    file:
      path: "{{ cert_path }}"
      state: directory
      owner: coyo
      group: coyo
  - name: "Generate the private key file to sign the CSR"
    openssl_privatekey:
      path: "{{ pempath }}"
      #cipher: aes256
  - name: "Generate the CSR file signed with the private key"
    openssl_csr:
      path: "{{ csrpath }}"
      privatekey_path: "{{ pempath }}"
      common_name: "{{ coyo_url }}"
  - name: "Sign the CSR file as a CA to turn it into a certificate"
    openssl_certificate:
      path: "{{ cert }}"
      privatekey_path: "{{ pempath }}"
      csr_path: "{{ csrpath }}"
      provider: selfsigned
  - name: Concatenate private key and certificate into a single file
    shell: "cat {{ pempath }} {{ cert }} > {{ cert_combined }}"
      creates: "{{ cert_combined }}"

  - name: Substitute COYO SSL certificate
    lineinfile:
      path: /home/coyo/.env
      regexp: '^COYO_CERT_FILE='
      line: 'COYO_CERT_FILE={{ cert_combined }}'

  - name: Start COYO setup script
    shell: ./start.sh
    args:
      chdir: /home/coyo/
    become: yes
    become_user: coyo

